application: van-ban-phap-luat
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS|json|JSON|doc|DOC|pdf|PDF))
  static_files: \1
  #mime_type: application/octet-stream
  upload: (.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS|json|JSON|doc|DOC|pdf|PDF))
  
- url: /css/(.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS))
  static_files: /css\1
  #mime_type: application/octet-stream
  upload: (.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS))

- url: /json/(.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS|json|JSON))
  static_files: /json\1
  mime_type: application/json
  upload: (.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS|json|JSON))

- url: /js/(.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS))
  static_files: /js\1
  #mime_type: application/octet-stream
  upload: (.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS))

- url: /images/(.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS))
  static_files: /images\1
  #mime_type: application/octet-stream
  upload: (.*\.(gif|GIF|png|PNG|jpg|JPG|ico|ICO|js|JS|css|CSS))
  
- url: /file/(.*\.(doc|DOC|pdf|PDF))
  static_files: /file\1
  #mime_type: application/octet-stream
  upload: (.*\.(doc|DOC|pdf|PDF))
  
- url: /fonts
  static_dir: fonts

- url: /app
  static_dir: app
  
- url: /(.+\.html)$ 
  script: \1 

- url: .*
  script: index.html
